### ISSUE TITLE
Can you write a detailed description of the overall workflow of the project？

### ISSUE THREAD

**Issue by PoKert-TT** [sengulhamza/esp32_lora_gateway#5]
After reading the code, I don't quite understand the meaning of gateway，Can you write a detailed description of the overall workflow of the project？

**Comment by sengulhamza** [comment]
Hi @zhangyyhh , 
The roadmap looks like this:
Lora layers and tasks have been written, but the gateway feature has not been added yet. I am planning to send lora data to MQTT broker as gateway. For this, first the connection layer, then the mqtt layer and data processing layer will be added. Rest api / web gui will also be added for the configuration of the whole device.
MQTT broker side work continues and lora gateway - broker auth and data structure are added to broker.
The next step is the OTA feature.

Thanks.

**Comment by sengulhamza** [comment]
@zhangyyhh Hi, 
wifi connection layer added into master.

**Comment by sengulhamza** [comment]
@zhangyyhh  Hi,

MQTT manager and publish layer added into master.
